// Code generated by "stringer -type=TagType -linecomment"; DO NOT EDIT.

package validator

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Min-0]
	_ = x[Name-1]
	_ = x[IP-2]
	_ = x[Password-3]
	_ = x[Max-4]
}

const _TagType_name = "MinnameippasswordMax"

var _TagType_index = [...]uint8{0, 3, 7, 9, 17, 20}

func (i TagType) String() string {
	if i < 0 || i >= TagType(len(_TagType_index)-1) {
		return "TagType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TagType_name[_TagType_index[i]:_TagType_index[i+1]]
}
