// Code generated by "stringer -type=ErrCode -linecomment"; DO NOT EDIT.

package berr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrUnknown - -1]
	_ = x[ErrorInvalidArgument-1001]
	_ = x[ErrorNotFound-1002]
	_ = x[ErrorPermissionDeny-1003]
	_ = x[ErrorWriteOnClose-1004]
}

const (
	_ErrCode_name_0 = "error unknown"
	_ErrCode_name_1 = "error argument invaliderror not founderror permission denyerror write on close"
)

var (
	_ErrCode_index_1 = [...]uint8{0, 22, 37, 58, 78}
)

func (i ErrCode) String() string {
	switch {
	case i == -1:
		return _ErrCode_name_0
	case 1001 <= i && i <= 1004:
		i -= 1001
		return _ErrCode_name_1[_ErrCode_index_1[i]:_ErrCode_index_1[i+1]]
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
