// Code generated by "stringer -type=ErrCode"; DO NOT EDIT.

package berr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrUnknown - -1]
	_ = x[ErrorInvalidArgument-1001]
	_ = x[ErrorRecordNotFound-1002]
	_ = x[ErrorPermissionDeny-1003]
}

const (
	_ErrCode_name_0 = "ErrUnknown"
	_ErrCode_name_1 = "ErrorInvalidArgumentErrorRecordNotFoundErrorPermissionDeny"
)

var (
	_ErrCode_index_1 = [...]uint8{0, 20, 39, 58}
)

func (i ErrCode) String() string {
	switch {
	case i == -1:
		return _ErrCode_name_0
	case 1001 <= i && i <= 1003:
		i -= 1001
		return _ErrCode_name_1[_ErrCode_index_1[i]:_ErrCode_index_1[i+1]]
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
