// Code generated by gen.sh. DO NOT EDIT.
package socket

import (
	"context"

	"brainwave/pkg/grpc/client"
	"brainwave/pkg/grpc/service"
	"google.golang.org/grpc"
)

func SendRpc(ctx context.Context, req *SendReq) (resp *SendRes, err error) {

	var conn *grpc.ClientConn
	if conn, err = client.GetConn(ctx, service.Service_socket_Socket); err != nil {
		return
	}

	cli := NewSocketClient(conn)
	if resp, err = cli.Send(ctx, req); err != nil {
		return
	}

	return
}
